### ISSUE TITLE
Link http://rudy.ca/doomsday is 404

### ISSUE THREAD

**Issue by johanbove** [kseistrup/doomsday#4]
Wanted to know more about what Doomsday is, but the link in the README is now ending in a 404 response unfortunately. Found another source for the description: https://www.timeanddate.com/date/doomsday-rule.html

**Comment by kseistrup** [comment]
Thanks for reporting this!

The URL has changed to `/doomsday.html`: https://rudy.ca/doomsday.html

I will look at it after coffee.
